apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample
  labels:
    app.kubernetes.io/name: "redpanda"
    app.kubernetes.io/instance: "redpandacluster-sample"
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 1
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      port: 9092
    admin:
      port: 9644
    developerMode: true
